let arr = [
  Indian Institute of Technology, Bhubaneswar,
  Indian Institute of Technology, Bombay,
  Indian Institute of Technology, Mandi,
  Indian Institute of Technology, Delhi,
  Indian Institute of Technology, Indore,
  Indian Institute of Technology, Kharagpur,
  Indian Institute of Technology, Hyderabad,
  Indian Institute of Technology, Jodhpur,
  Indian Institute of Technology, Kanpur,
  Indian Institute of Technology, Madras,
  Indian Institute of Technology, Gandhinagar,
  Indian Institute of Technology, Patna,
  Indian Institute of Technology, Roorkee,
  Indian Institute of Technology (Indian School of Mines), Dhanbad,
  Indian Institute of Technology, Ropar,
  Indian Institute of Technology (Banaras Hindu University), Varanasi,
  Indian Institute of Technology, Guwahati,
  Indian Institute of Technology, Bhilai,
  Indian Institute of Technology, Goa,
  Indian Institute of Technology, Palakkad,
  Indian Institute of Technology, Tirupati,
  Indian Institute of Technology, Jammu,
  Indian Institute of Technology, Dharwad,
  Dr. B R Ambedkar National Institute of Technology, Jalandhar,
  Malaviya National Institute of Technology, Jaipur,
  Maulana Azad National Institute of Technology, Bhopal,
  Motilal Nehru National Institute of Technology, Allahabad,
  National Institute of Technology, Agartala,
  National Institute of Technology, Calicut,
  National Institute of Technology, Delhi,
  National Institute of Technology, Durgapur,
  National Institute of Technology, Goa,
  National Institute of Technology, Hamirpur,
  National Institute of Technology Karnataka, Surathkal,
  National Institute of Technology, Meghalaya,
  National Institute of Technology, Nagaland,
  National Institute of Technology, Patna,
  National Institute of Technology, Puducherry,
  National Institute of Technology, Raipur,
  National Institute of Technology, Sikkim,
  National Institute of Technology, Arunachal Pradesh,
  National Institute of Technology, Jamshedpur,
  National Institute of Technology, Kurukshetra,
  National Institute of Technology, Manipur,
  National Institute of Technology, Mizoram,
  National Institute of Technology, Rourkela,
  National Institute of Technology, Silchar,
  National Institute of Technology, Srinagar,
  National Institute of Technology, Tiruchirapalli,
  National Institute of Technology, Uttarakhand,
  National Institute of Technology, Warangal,
  Sardar Vallabhbhai National Institute of Technology, Surat,
  Visvesvaraya National Institute of Technology, Nagpur,
  National Institute of Technology, Andhra Pradesh,
  Indian Institute of Information Technology and Management, Gwalior,
  Indian Institute of Information Technology, Kota,
  Indian Institute of Information Technology, Guwahati,
  Indian Institute of Information Technology, Kalyani,
  Indian Institute of Information Technology, Sonepat,
  Indian Institute of Information Technology, Una,
  Indian Institute of Information Technology, Sri City,
  Indian Institute of Information Technology, Vadodara,
  Indian Institute of Information Technology, Allahabad,
  Indian Institute of Information Technology Design & Manufacturing, Kancheepuram,
  Indian Institute of Information Technology Design & Manufacturing, Jabalpur,
  Indian Institute of Information Technology, Manipur,
  Indian Institute of Information Technology, Tiruchirapalli,
  Indian Institute of Information Technology, Lucknow,
  Indian Institute of Information Technology, Dharwad,
  Indian Institute of Information Technology Design and Manufacturing, Kurnool,
  Indian Institute of Information Technology, Kottayam,
  Indian Institute of Information Technology, Ranchi,
  Indian Institute of Information Technology, Nagpur,
  Indian Institute of Information Technology, Pune,
  Triguna Sen School of Technology, Assam University, Silchar,
  Birla Institute of Technology, Mesra,
  Gurukula Kangri Vishwavidyalaya, Haridwar,
  Indian Institute of Engineering Science and Technology, Shibpur,
  Institute of Infrastructure, Technology, Research and Management (IITRAM), Ahmedabad,
  J.K. Institute of Applied Physics and Technology, Allahabad,
  Birla Institute of Technology and Science, Pilani,
  Birla Institute of Technology and Science, Goa,
  Birla Institute of Technology and Science, Hyderabad,
  Netaji Subhas University of Technology, Delhi,
  Delhi Technological University,
  Indira Gandhi Delhi Technical University for Women,
  Indraprastha Institute of Information Technology, Delhi,
  Dhirubhai Ambani Institute of Information and Communication Technology,
  Thapar Institute of Engineering and Technology, Patiala,
  International Institute of Information Technology, Hyderabad,
  International Institute of Information Technology, Bangalore,
  LNM Institute of Information Technology,
  Indian Institute of Science, Bangalore,
  Jaypee Institute of Information Technology (Sector-62 Campus), Noida,
  Jaypee Institute of Information Technology (Sector-128 Campus), Noida,
  Vellore Institute of Technology, Vellore,
  Vellore Institute of Technology (Chennai Campus),
  Faculty of Engineering and Technology, Jamia Millia Islamia, Delhi,
  Indian Institute of Space Science and Technology, Thiruvananthapuram,
  Institute of Technology, Nirma University,
  Zakir Husain College of Engineering & Technology, Aligarh,
  Indian Institute of Science Education and Research, Pune,
  Indian Institute of Science Education and Research, Mohali,
  Indian Institute of Science Education and Research, Bhopal,
  Indian Institute of Science Education and Research, Kolkata,
  Indian Institute of Science Education and Research, Thiruvananthapuram,
  Indian Institute of Science Education and Research, Tirupati,
  Indian Institute of Science Education and Research, Berhampur,
  School of Engineering - UPES, Dehradun,
  National Institute of Science Education and Research, Bhubaneswar,
  International Institute of Information Technology, Bhubaneswar,
  Harcourt Butler Technical University, Kanpur,
  Jadavpur University, Kolkata,
  Institute of Engineering & Technology, Lucknow,
  Punjab Engineering College, Chandigarh,
  University Institute of Engineering and Technology, Panjab University, Chandigarh,
  Cochin University of Science and Technology, Kochi,
  Manipal Institute of Technology,
  JNTUH College of Engineering, Hyderabad,
  College of Engineering, Pune,
  Veermata Jijabai Technological Institute, Mumbai,
  VIT-AP University, Andhra Pradesh,
  VIT Bhopal University, Madhya Pradesh,
  University School of Information, Communication & Technology, Delhi,
  Maharaja Agrasen Institute of Technology, Delhi,
  Bharati Vidyapeeth's College of Engineering, New Delhi,
  Dr. Akhilesh Das Gupta Institute of Technology and Management, Delhi,
  Guru Tegh Bahadur Institute of Technology, Delhi,
  Maharaja Surajmal Institute of Technology, Delhi,
  Bhagwan Parshuram Institute of Technology, Delhi,
  R.V. College of Engineering, Bangalore,
  BMS College of Engineering, Bangalore,
  Ramaiah Institute of Technology, Bangalore,
  PES University Ring Road Campus, Bangalore,
  PES University Electronic City Campus, Bangalore,
  BMS Institute of Technology and Management, Bangalore,
  University Visvesvaraya College of Engineering, Bangalore,
  Sir M Visvesvaraya Institute of Technology, Bangalore,
  MVJ College of Engineering, Bangalore,
  The National Institute of Engineering, Mysore,
  Kalyani Government Engineering College, Kalyani,
  Pune Institute of Computer Technology, Pune,
  J.C. Bose University of Science and Technology, YMCA, Faridabad,
  Army Institute of Technology, Pune,
  Walchand College of Engineering, Sangli,
  Bangalore Institute of Technology, Bangalore,
  Sardar Patel College of Engineering, Mumbai,
  Dwarkadas J. Sanghvi College of Engineering, Mumbai,
  Vishwakarma Institute of Technology, Pune,
  Dr. Vishwanath Karad MIT World Peace University, Pune,
  Shri Govindram Seksaria Institute of Technology and Science, Indore,
  Institute of Engineering and Technology Devi Ahilya Vishawvidyalaya, Indore,
  Indian Institute of Information Technology, Bhagalpur,
  Indian Institute of Information Technology, Bhopal,
  Indian Institute of Information Technology, Surat,
  Dr. SPM International Institute of Information Technology, Naya Raipur,
  Rajiv Gandhi Institute of Petroleum Technology, Amethi,
  College of Engineering, Trivandrum,
  Institute of Chemical Technology, Mumbai,
  Indian Institute of Information Technology, Agartala,
  School of Engineering, Jawaharlal Nehru University, Delhi,
  Amity School of Engineering and Technology, Noida,
  Amity School of Engineering, Noida,
  Netaji Subhas University of Technology (East Campus), Delhi,
  Sri Jayachamarajendra College of Engineering, Mysore,
  Siddaganga Institute of Technology, Tumkur,
  KLE Technological University, Hubli,
  Dayananda Sagar College of Engineering, Bangalore,
  TKM College of Engineering, Kollam,
  Government Engineering College, Thrissur,
  Government Model Engineering College, Kochi,
  Sardar Patel Institute of Technology, Mumbai,
  K.J. Somaiya College of Engineering, Mumbai,
  Jabalpur Engineering College, Jabalpur,
  Madhav Institute of Technology and Science, Gwalior,
  Institute of Engineering and Management, Kolkata,
  Indian Institute of Petroleum and Energy, Visakhapatnam,
  Dr. S. S. Bhatnagar University Institute of Chemical Engineering and Technology, Chandigarh,
  Indian Institute of Information Technology, Raichur,
  Cummins College of Engineering for Women, Pune,
  Heritage Institute of Technology, Kolkata,
  University of Calcutta, Kolkata,
  IIIT Vadodara - International Campus Diu,
  Netaji Subhas University of Technology (West Campus), Delhi,
  University College of Engineering, Osmania University, Hyderabad,
  Chaitanya Bharathi Institute of Technology, Hyderabad,
  Vasavi College of Engineering, Hyderabad,
  VNR Vignana Jyothi Institute of Engineering and Technology, Hyderabad,
  Gokaraju Rangaraju Institute of Engineering and Technology, Hyderabad,
  CVR College of Engineering, Ibrahimpatnam,
  Andhra University College of Engineering, Visakhapatnam,
  University College of Engineering, Kakinada,
  SVU College of Engineering, Tirupati,
  University School of Automation & Robotics, Delhi,
  Birsa Institute of Technology, Sindri,
  SRM Institute of Science and Technology, Chennai,
  Amrita School of Engineering, Coimbatore,
  Jalpaiguri Government Engineering College, Jalpaiguri,
  Maulana Abul Kalam Azad University of Technology, Kolkata,
  Manipal Institute of Technology, Bengaluru,
  School of Computer and Information Sciences, University of Hyderabad,
  JSS Science and Technology University, Mysore,
];
